//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDriver.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentHealthRecordDBEntities : DbContext
    {
        public StudentHealthRecordDBEntities()
            : base("name=StudentHealthRecordDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIPendingTable> APIPendingTables { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<StudentHealthRecordTable> StudentHealthRecordTables { get; set; }
        public virtual DbSet<PublicHealthRecordTable> PublicHealthRecordTables { get; set; }
    }
}
