using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
    public class PublicHealthRecordModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StudentNum { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Birthplace { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string ContactNum { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherContactNum { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherContactNum { get; set; }
        public string GuardianName { get; set; }
        public string GuardianOccupation { get; set; }
        public string GuardianContactNum { get; set; }
        public string HospitalofChoice { get; set; }
        public string AddressofHospital { get; set; }
        public string HospitalContactNum { get; set; }
        public string NameofFamilyDoctor { get; set; }
        public string Allergy { get; set; }
        public string PastAsthma { get; set; }
        public string Anemia { get; set; }
        public string BleedingProblem { get; set; }
        public string BehavioralProblem { get; set; }
        public string HearingProblem { get; set; }
        public string SpeechProblem { get; set; }
        public string VisualProblem { get; set; }
        public string RecurrentIndigestion { get; set; }
        public string Jaundice { get; set; }
        public string EatingDisorder { get; set; }
        public string ChickenFox { get; set; }
        public string DengueFever { get; set; }
        public string ThypoidFever { get; set; }
        public string Measles { get; set; }
        public string Mumps { get; set; }
        public string Pneumonia { get; set; }
        public string PrimaryComplex { get; set; }
        public string EarDischarge { get; set; }
        public string Tonsilitis { get; set; }
        public string Parasitism { get; set; }
        public string Insomnias { get; set; }
        public string HeartDisease { get; set; }
        public string KidneyDisease { get; set; }
        public string Convulsion { get; set; }
        public string Epilepsy { get; set; }
        public string PastDiabetes { get; set; }
        public string Fainting { get; set; }
        public string Fractures { get; set; }
        public string Scolosis { get; set; }
        public string Hospitalization { get; set; }
        public string Operation { get; set; }
        public string Cancer { get; set; }
        public string CancerRelation { get; set; }
        public string HeartProblem { get; set; }
        public string HeartRelationProblem { get; set; }
        public string HighBlood { get; set; }
        public string HighBloodRelation { get; set; }
        public string FamilyDiabetes { get; set; }
        public string DiabetesRelation { get; set; }
        public string KidneyProblem { get; set; }
        public string KidneyProblemRelation { get; set; }
        public string SeizureDisorder { get; set; }
        public string SeizureDisorderRelation { get; set; }
        public string Tubercolosis { get; set; }
        public string TubercolosisRelation { get; set; }
        public string FamilyAsthma { get; set; }
        public string AsthmaRelation { get; set; }
        public string BleedingDisorder { get; set; }
        public string BleedingDisorderRelation { get; set; }
        public string MentalDisorder { get; set; }
        public string MentalDisorderRelation { get; set; }
        public string Stroke { get; set; }
        public string StrokeRelation { get; set; }
        public string Obesity { get; set; }
        public string ObesityRelation { get; set; }
        public string Physical { get; set; }
        public string PhysicalRelevantDetails { get; set; }
        public string Sexual { get; set; }
        public string SexualRelevantDetails { get; set; }
        public string Verval { get; set; }
        public string VervalRelevantDetails { get; set; }
        public string AOOOGE { get; set; }
        public string AOOOPH { get; set; }
        public string Hernia { get; set; }
        public Nullable<System.DateTime> HerniaDate { get; set; }
        public string Circumcision { get; set; }
        public string CircumcisionDate { get; set; }
        public string AOOOM { get; set; }
        public string RegularCycle { get; set; }
        public string Flow { get; set; }
        public string Discomfort { get; set; }
        public string HeadA { get; set; }
        public string HeadB { get; set; }
        public string HeadC { get; set; }
        public string EyesA { get; set; }
        public string EyesB { get; set; }
        public string EyesC { get; set; }
        public string ENTA { get; set; }
        public string ENTB { get; set; }
        public string ENTC { get; set; }
        public string ENTD { get; set; }
        public string ENTE { get; set; }
        public string ENTF { get; set; }
        public string ENTG { get; set; }
        public string ENTH { get; set; }
        public string ENTI { get; set; }
        public string ENTJ { get; set; }
        public string ENTK { get; set; }
        public string ENTL { get; set; }
        public string ENTM { get; set; }
        public string ENTN { get; set; }
        public string ENTO { get; set; }
        public string NeckA { get; set; }
        public string NeckB { get; set; }
        public string HLA { get; set; }
        public string HLB { get; set; }
        public string HLC { get; set; }
        public string HLD { get; set; }
        public string HLE { get; set; }
        public string HLF { get; set; }
        public string HLG { get; set; }
        public string HLH { get; set; }
        public string HLI { get; set; }
        public string HLJ { get; set; }
        public string AbdomenA { get; set; }
        public string AbdomenB { get; set; }
        public string AbdomenC { get; set; }
        public string AbdomenD { get; set; }
        public string AbdomenE { get; set; }
        public string AbdomenF { get; set; }
        public string AbdomenG { get; set; }
        public string AbdomenH { get; set; }
        public string AbdomenI { get; set; }
        public string AbdomenJ { get; set; }
        public string AbdomenK { get; set; }
        public string AbdomenL { get; set; }
        public string BoneJointA { get; set; }
        public string BoneJointB { get; set; }
        public string BoneJointC { get; set; }
        public string BoneJointD { get; set; }
        public string BoneJointE { get; set; }
        public string BoneJointF { get; set; }
        public string BoneJointG { get; set; }
        public string BoneJointH { get; set; }
        public string BoneJointI { get; set; }
        public string BoneJointJ { get; set; }
        public string NervousSystemA { get; set; }
        public string NervousSystemB { get; set; }
        public string NervousSystemC { get; set; }
        public string NervousSystemD { get; set; }
        public string NervousSystemE { get; set; }
        public string NervousSystemF { get; set; }
        public string NervousSystemG { get; set; }
        public string ChronicDiseasesA { get; set; }
        public string ChronicDiseasesB { get; set; }
        public string ChronicDiseasesC { get; set; }
        public string ChronicDiseasesD { get; set; }
        public string ChronicDiseasesE { get; set; }
        public string ChronicDiseasesF { get; set; }
        public string InfectiousDiseasesA { get; set; }
        public string InfectiousDiseasesB { get; set; }
        public string InfectiousDiseasesC { get; set; }
        public string InfectiousDiseasesD { get; set; }
        public string InfectiousDiseasesE { get; set; }
        public string InfectiousDiseasesF { get; set; }
        public string InfectiousDiseasesG { get; set; }
        public string InfectiousDiseasesH { get; set; }
        public string InfectiousDiseasesI { get; set; }
        public string InfectiousDiseasesJ { get; set; }
        public string InfectiousDiseasesK { get; set; }
        public string MedicineA { get; set; }
        public string MedicineB { get; set; }
        public string MedicineC { get; set; }
        public string MedicineD { get; set; }
        public string MedicineE { get; set; }
        public string MedicineF { get; set; }
        public string MedicineG { get; set; }
        public string MedicineH { get; set; }
        public string MedicineI { get; set; }
        public string UnfavorableA { get; set; }
        public string UnfavorableB { get; set; }
        public string UnfavorableC { get; set; }
        public string UnfavorableD { get; set; }
        public string UnfavorableE { get; set; }
        public string UnfavorableF { get; set; }
        public string HeadAAge { get; set; }
        public string HeadBAge { get; set; }
        public string HeadCAge { get; set; }
        public string EyesAAge { get; set; }
        public string EyesBAge { get; set; }
        public string EyesCAge { get; set; }
        public string ENTAAge { get; set; }
        public string ENTBAge { get; set; }
        public string ENTCAge { get; set; }
        public string ENTDAge { get; set; }
        public string ENTEAge { get; set; }
        public string ENTFAge { get; set; }
        public string ENTGAge { get; set; }
        public string ENTHAge { get; set; }
        public string ENTIAge { get; set; }
        public string ENTJAge { get; set; }
        public string ENTKAge { get; set; }
        public string ENTLAge { get; set; }
        public string ENTMAge { get; set; }
        public string ENTNAge { get; set; }
        public string ENTOAge { get; set; }
        public string NeckAAge { get; set; }
        public string NeckBAge { get; set; }
        public string HLAAge { get; set; }
        public string HLBAge { get; set; }
        public string HLCAge { get; set; }
        public string HLDAge { get; set; }
        public string HLEAge { get; set; }
        public string HLFAge { get; set; }
        public string HLGAge { get; set; }
        public string HLHAge { get; set; }
        public string HLIAge { get; set; }
        public string HLJAge { get; set; }
        public string AbdomenAAge { get; set; }
        public string AbdomenBAge { get; set; }
        public string AbdomenCAge { get; set; }
        public string AbdomenDAge { get; set; }
        public string AbdomenEAge { get; set; }
        public string AbdomenFAge { get; set; }
        public string AbdomenGAge { get; set; }
        public string AbdomenHAge { get; set; }
        public string AbdomenIAge { get; set; }
        public string AbdomenJAge { get; set; }
        public string AbdomenKAge { get; set; }
        public string AbdomenLAge { get; set; }
        public string BoneJointAAge { get; set; }
        public string BoneJointBAge { get; set; }
        public string BoneJointCAge { get; set; }
        public string BoneJointDAge { get; set; }
        public string BoneJointEAge { get; set; }
        public string BoneJointFAge { get; set; }
        public string BoneJointGAge { get; set; }
        public string BoneJointHAge { get; set; }
        public string BoneJointIAge { get; set; }
        public string BoneJointJAge { get; set; }
        public string NervousSystemAAge { get; set; }
        public string NervousSystemBAge { get; set; }
        public string NervousSystemCAge { get; set; }
        public string NervousSystemDAge { get; set; }
        public string NervousSystemEAge { get; set; }
        public string NervousSystemFAge { get; set; }
        public string NervousSystemGAge { get; set; }
        public string ChronicDiseasesAAge { get; set; }
        public string ChronicDiseasesBAge { get; set; }
        public string ChronicDiseasesCAge { get; set; }
        public string ChronicDiseasesDAge { get; set; }
        public string ChronicDiseasesEAge { get; set; }
        public string ChronicDiseasesFAge { get; set; }
        public string InfectiousDiseasesAAge { get; set; }
        public string InfectiousDiseasesBAge { get; set; }
        public string InfectiousDiseasesCAge { get; set; }
        public string InfectiousDiseasesDAge { get; set; }
        public string InfectiousDiseasesEAge { get; set; }
        public string InfectiousDiseasesFAge { get; set; }
        public string InfectiousDiseasesGAge { get; set; }
        public string InfectiousDiseasesHAge { get; set; }
        public string InfectiousDiseasesIAge { get; set; }
        public string InfectiousDiseasesJAge { get; set; }
        public string InfectiousDiseasesKAge { get; set; }
        public string MedicineAAge { get; set; }
        public string MedicineBAge { get; set; }
        public string MedicineCAge { get; set; }
        public string MedicineDAge { get; set; }
        public string MedicineEAge { get; set; }
        public string MedicineFAge { get; set; }
        public string MedicineGAge { get; set; }
        public string MedicineHAge { get; set; }
        public string MedicineIAge { get; set; }
        public string UnfavorableAAge { get; set; }
        public string UnfavorableBAge { get; set; }
        public string UnfavorableCAge { get; set; }
        public string UnfavorableDAge { get; set; }
        public string UnfavorableEAge { get; set; }
        public string UnfavorableFAge { get; set; }
        public string OMIOS1 { get; set; }
        public string OMIOS11 { get; set; }
        public string OMIOS12 { get; set; }
        public string OMIOS13 { get; set; }
        public string OMIOS2 { get; set; }
        public string OMIOSB22 { get; set; }
        public string OMIOS3 { get; set; }
        public string OMIOS33 { get; set; }
        public string OMIOS34 { get; set; }
        public string OMIOS35 { get; set; }
        public string OMIOS36 { get; set; }
        public string OMIOS4 { get; set; }
        public string OMIOS44 { get; set; }
        public string OMIOS5 { get; set; }
        public string OMIOS6 { get; set; }
        public string OMIOS66 { get; set; }
        public string ConcentName { get; set; }
        public string ConsentRelationship { get; set; }
    }
}
